---
apiVersion: v1
kind: Service
metadata:
  name: brice
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: brice


